### ISSUE TITLE
Notifications: mark all as read button, number bubble in bottom navigation

### ISSUE THREAD

**Issue by tclaus** [jhass/insporation#18]
![image](https://user-images.githubusercontent.com/501326/97916970-0d263c00-1d54-11eb-9061-5533c0ff3077.jpeg)

The bell has no number.
![image](https://user-images.githubusercontent.com/501326/97917037-25965680-1d54-11eb-9ef1-ce2a6c740981.jpeg)

The badge should be cleared when opening the alerts - tag. 
Currently one need to open all new alerts. A "Mark all read" button is also missing. 

Better: clear tab bell aber visiting the tab.

**Comment by jhass** [comment]
Mark all as read is a no brainer :+1:

Personally I like the reminder and actively keep notifications unread that I still want to react to, to the point of marking stuff unread after I initially read them. 

So maybe this is a good thing to do a little user poll about :)

**Comment by tclaus** [comment]
If there is a 'mark all' on top of the list - it's absolut OK. Then the badge must not vanish on open the tab. 
But I still like to see a number inside it. 
Then function is symmetrical to what I see in the web-ui.

**Comment by jhass** [comment]
Mmh, I'm not entirely confident there's enough space for such a bubble on all devices, but let's try it out :)
