### ISSUE TITLE
Bug/Usability: when opening ‚switch User‘ User is logged out immediately

### ISSUE THREAD

**Issue by tclaus** [jhass/insporation#19]
When someone is just curious what "switch user" means.. 
![image](https://user-images.githubusercontent.com/501326/97917503-da307800-1d54-11eb-8b86-51f50601e369.jpeg)

There is no way to go back. "Cancel"

But you can just swipe right to go back to the main Ui. 
But then the current user is logged out. 
![image](https://user-images.githubusercontent.com/501326/97917605-ffbd8180-1d54-11eb-8bb1-bae2e18b09af.jpeg)

Bettler: when opening "switch user" (the login screen) from a logged in instance. Don't clear logged-in status. Until new credentials are entered. 
Provide a cancel option.

**Comment by jhass** [comment]
Ah,  I don't think I have  a way to go back on Android, or at least I never tried... we probably should make sure to clear the navigation stack here.

So I've been thinking, there's no need to clear the session on this just yet. So we could show a list of active sessions on the sign in page that you can just click on to reenter, and possibly have an action button there to delete a session. What do you think?

**Comment by tclaus** [comment]
Like the idea and would solve the UI-problem. 
A horizontale line of active accounts, with a X somewhere, and a 'Add Account' button. 
Maybe ist wise to limit maximum accounts supported. 
The is the Facebook solution: right beside 'Victor' there is a "Login-panel'. It should be scrollable. 

<img width="362" alt="Bildschirmfoto 2020-11-03 um 08 00 08" src="https://user-images.githubusercontent.com/501326/97957289-0d9df180-1dab-11eb-8c9a-c4a8d250b69e.png">

**Comment by jhass** [comment]
To keep it simple for starters I would go with just a list, something like:


```

+---------------------------------+
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
|        +------------------+     |
|        |   Enter user@pod |     |
|        +------------------+     |
|                                 |
|        +-------------+  X       |
|                                 |
|        +-------------+  X       |
|                                 |
|        +-------------+  X       |
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
|                                 |
+---------------------------------+

```

and yeah, limit it to the 5 most recently used entries, also sort by most recently used.

**Comment by tclaus** [comment]
Absolut - like the simplicity of this.
