### ISSUE TITLE
Proposal: Easier switching of accounts

### ISSUE THREAD

**Issue by Ravenbird** [jhass/insporation#24]
Would it be useful or feasible to create a separate menu item for changing the accounts in the bar, which then uses the profile picture of the currently active account? This would show you which account is currently active and you could change faster if necessary.

**Comment by jhass** [comment]
I'm not sure if it's really such a primary usecase for many users to warrant first class UI in this highly contended UI estate. I think most people only maintain a single account.

I'm pretty happy with #20 making it pretty easy to resume another session.

**Comment by Ravenbird** [comment]
It was just an idea, in the long run I think there will be more possibilities and then you have to find a way to accommodate that. For example into a side menu or something like that. But now I think you are on a very good course and I can only thank you for your work.

**Comment by jhass** [comment]
Let's see if my little poll confirms or rejects my premise :) https://diaspora.social/posts/207559

**Comment by Ravenbird** [comment]
A good idea, I'll share this with the others. :-)

**Comment by jhass** [comment]
So I think participation quieted down I think, let's take a look at the results.

Over 85% of users do not switch between accounts on a daily basis, reality is probably even higher than that because given the low turnout we can expect power users to be over-represented in the results.

I don't think this warrants a permanently visible UI element :)

**Comment by Ravenbird** [comment]
Sorry for the late reply. You're right after the concept it doesn't fit in the bar below. Maybe there will be a menu on the side to pull out and put it in the appropriate place.

**Comment by jhass** [comment]
Closing this for now, as it's unlikely something to be changed / worked on soon. Of course it's perfectly fine for any discussion to continue.
