### ISSUE TITLE
Proposal: Let the user choose whether to have the bar at the top or bottom

### ISSUE THREAD

**Issue by Ravenbird** [jhass/insporation#25]
One of the first things I noticed about Insporation was that the bar was at the bottom and not at the top. I can live with that in an emergency, but I would prefer to have the bar at the top, as in the Diaspora web interface, or leave it up to the user to decide whether the bar is at the top or bottom. For me, a bar at the top is not only a habit, but also the fact that it is located directly above the Android bar when it is at the bottom and in the heat of the moment you can easily get the wrong button.

![signal-2020-11-10-101602](https://user-images.githubusercontent.com/2757648/98653889-e06ab980-233d-11eb-9471-d7b0da4284b5.jpeg)

**Comment by jhass** [comment]
This design element is called a bottom navigation bar and the standard for new apps these days. It's likely something we will not change, sorry.

See https://material.io/components/bottom-navigation

**Comment by tclaus** [comment]
read this for iOS design principles: https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/

Its better to follow App design guidelines on its specific platform than to try to mimic web design.

**Comment by Ravenbird** [comment]
OK that makes sense to me as far as pure navigation is concerned. But as soon as the notifications are running over it it is in my eyes that they are better visible at the top of the page than at the bottom. Apart from the problem I described that the Android bar is directly below. In the end it's up to you Jonne, I can live with it.
