### ISSUE TITLE
Proposal: Add a social media sharing button to every post 

### ISSUE THREAD

**Issue by Ravenbird** [jhass/insporation#26]
With Diaspora's web interface it is easy to copy the address of a post to share it. Unfortunately, this is not possible with Inspiration. Therefore it would be good to have a button to pass it on to other media and to copy the address.

**Comment by jhass** [comment]
So the "right way" to do this would be for the API to return something like a `share_url` property for the post, which it currently doesn't. So right now the client could only do this by making assumptions about what the URL should be.

**Comment by Ravenbird** [comment]
Yeah you are right. If not, the question is whether the API works with the normal Post-IDs on the respective post. If this is the case, you can use it to create a suitable URL. For example, if you have the Post-ID 8869742 for an account on nerdpol.ch, this is what you get:

https://nerdpol.ch/posts/8869742

But if the API works with something completely different it becomes really difficult.

I think that such a button could also lead to people sharing more public Diaspora contributions and thus make Diaspora better known.

**Comment by jhass** [comment]
It works with the post guids, so we could quite easily construct `https://<currently signed in users hostname>/posts/<guid>`, which diaspora currently accepts too on that route. It's just a ton of assumptions in that still :)

**Comment by Ravenbird** [comment]
Two guys, one idea. :-)

**Comment by tclaus** [comment]
It then could simply be the platform-specific 'share' button. No frills.

**Comment by jhass** [comment]
I mean we also have the `diaspora://<diasporaId>/posts/<guid>` (or so, don't quite remember the exact format) custom deeplink, I just doubt a lot of users have that registered :P

**Comment by jhass** [comment]
I'm fine with guessing for now, but nonetheless opened https://github.com/diaspora/api-documentation/issues/58 for handling this properly at some point.

**Comment by tclaus** [comment]
I have prepared something. 
PR soon.
