### ISSUE TITLE
Reshare: Link to original post

### ISSUE THREAD

**Issue by DeusFigendi** [jhass/insporation#4]
I am missing a link to the original post in reshared posts in my streamview.

That is especially important because of the "please comment at the origin post"-policy :)

Since the content of the post itself is identical, I think the easiest and most sane way to do so would be to offer **two** comment-buttons, one for the reshare the user is looking at and one for the original post. Depending which one is tabbed other comments are loaded (and the own comment is sent to).
Unfortunately this could also be confusing to some users… but I think it would be cool XD

**Comment by jhass** [comment]
Yeah, the big question is how to do nice UX for this. Two comment buttons is a... not so good idea in my opinion :P 

I'm almost inclined to send all likes and comments to the original post always.

**Comment by DeusFigendi** [comment]
> I'm almost inclined to send all likes and comments to the original post always.

I don't think that's a good idea, this way the user cannot access the discussion of the reshare. And I don't think these ain't important.

Here are four UX ideas to solve this (sorry for the German interface I was to lazy to switch):

### all the comments in one column

![all_the_comments](https://user-images.githubusercontent.com/1711504/78419943-fea36500-764a-11ea-82af-5fda2c65bb1d.jpg)

Here are the comments of the reshare and the comments of the original are just aligned below each other. So the user first sees the comments of the reshare she was looking at and can comment that discussion, but she also can scroll to the comments of the original.

----

### swipe for the original post

![swipe_right_a](https://user-images.githubusercontent.com/1711504/78419977-53df7680-764b-11ea-87a0-a7de97eaea91.jpg)

A **few** days ago I realized that I can swipe right to enter the special-features for a post. Cool thing!!! So I had the idea one could swipe left to swap the reshare for the original post (but I'd guess this is difficult to build inside a streamlike view).
Another idea that just comes to my mind: Why not add a "link to the original" on that left column?

----
### swipe for the originals comments

![swipe_right_b](https://user-images.githubusercontent.com/1711504/78420014-b173c300-764b-11ea-9e7b-30ac60025b70.jpg)

And this is somehow a combination of the two above. The user opens the reshare's comments and than she can swipe to the left to get the discussion at the original post (in the background you can see that the post itself is also the original, I don't know if that is important to the user).

----
### two comments buttons

![two_comment_icons](https://user-images.githubusercontent.com/1711504/78420056-01eb2080-764c-11ea-93ad-cfe6fc7dc6f7.jpg)

And this was my very first idea I drafted two days ago…

> Since the content of the post itself is identical, I think the easiest and most sane way to do so would be to offer two comment-buttons, one for the reshare the user is looking at and one for the original post.

**Comment by jhass** [comment]
Thanks for the many ideas! I think I would like to keep it simple for now, so yes, maybe just a link in the extended post actions would be good.
