### ISSUE TITLE
notification counter only goes up to 15

### ISSUE THREAD

**Issue by Waithamai** [jhass/insporation#43]
The number of notifications displayed with the bell icon only counts up to 15, then stays at 15 even if there are more unread notifications. If you go to the notifications page, all notifications are there, it's only a bug in the displayed number.

**Comment by jhass** [comment]
Ah, that's because it only fetches the first page of notifications. I'm hesitant to fetch multiple pages for this, how does displaying "9+" if there's 10 or more unread notifications sound?

**Comment by tclaus** [comment]
If you are on this..
What's about removing the batch after opening the navigation tab? (But let the individual entries in state "unread")?

**Comment by jhass** [comment]
That requires tracking the seen status of notifications to substract them from the unread ones. And it has the same issue, there could be more than one page of unread and unseen notifications. So overall it seems to increase complexity.

From a user experience I like keeping the badge better too, but then I'm the kind of "keep unread as todo" person.

**Comment by jhass** [comment]
I changed it to only count up to 9 for now and display a + when there's more. I think that's the least confusing UX for now without an API endpoint for returning the full unread count.

Of course none of that is set it stone :)
