### ISSUE TITLE
Strange behaviour when hiding a post

### ISSUE THREAD

**Issue by tclaus** [jhass/insporation#46]
I swipe right, to see the secondary buttons, tap on the "eye" (hide post?) and get a black screen.  
Latest version, iOS. 
https://user-images.githubusercontent.com/501326/118884978-6e2fee80-b8f7-11eb-9436-be6abf7eb633.MOV

**Comment by jhass** [comment]
Does not seem to reproduce for me, not on first try anyhow.

**Comment by tclaus** [comment]
Maybe an iOS effect only? 
I'll test it on different pods.

**Comment by jhass** [comment]
🤷 

Definitely worth to try a debug build and checking the logs for failed assertions.

**Comment by tclaus** [comment]
> 🤷
> 
> Definitely worth to try a debug build and checking the logs for failed assertions.

On my way..

**Comment by tclaus** [comment]
In currentBuild (161) this is no longer reproducible
