### ISSUE TITLE
After approving access to insporation from pod getting net::ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by simong1080** [jhass/insporation#47]
![Screenshot_20210527-191853_Browser](https://user-images.githubusercontent.com/16803653/120792879-d9f09900-c53e-11eb-869d-3d87ca0d6a91.png)

**Comment by jhass** [comment]
Huh, which browser and Android version is that?

**Comment by simong1080** [comment]
> Huh, which browser and Android version is that?

Stock browser lineageOS
![Screenshot_20210605-211018_Settings](https://user-images.githubusercontent.com/16803653/120901363-0d1c5080-c643-11eb-9eb2-790c612b0bc8.png)

**Comment by simong1080** [comment]
Switched default browser and it worked
