### ISSUE TITLE
F-Droid app can't be found

### ISSUE THREAD

**Issue by cunningdavid** [jhass/insporation#50]
This github project says that:

"The nightlies are also published to a F-Droid repository which you can add by scanning the following QR code:"
or clicking this link on your device that has F-Droid installed."

However a search for "insporation" on F-Droid gives no results, and if I click on that link on my device with F-Droid installed I see the raw XML data.

Is the app really on F-Droid, or might I be missing something? Thank you!

**Comment by Flaburgan** [comment]
As it is explained, it is not in the default F-Droid repository, you need to add the repository by scanning the QR code from F-Droid.

**Comment by cunningdavid** [comment]
Ah, thank you. Where in F-Droid can you scan a QR code? I can't find the option.

**Comment by cunningdavid** [comment]
I couldn’t find anywhere in F-Droid to scan a QR code, but have now found the Settings → Repositories → + option and copied the URL to install it.

Does anyone know a public pod running the develop branch that I could test it with?

**Comment by Flaburgan** [comment]
You can register on mine, https://diaspora-fr.org
