### ISSUE TITLE
Properly handle failing discovery on unsupported servers

### ISSUE THREAD

**Issue by norayr** [jhass/insporation#6]
sorry if opening an issue is not a right way to deal with this.
you can close it then.

so, i have tried it wtih two jids - one at spyurk.am, other at joindiaspora.com.
after entering jid on the first screen, i see the continuously loading screen, forever.

os: lineageos-17.1, it is android 10

**Comment by jhass** [comment]
https://version.diaspora.social/spyurk.am

> The pod runs on 0.7.14.0.

https://version.diaspora.social/joindiaspora.com

> The pod runs on 0.7.14.0.

README.md:

> This is still in preview. You will need a pod on the latest develop branch.

I guess the error handling around this could be better though :)

**Comment by norayr** [comment]
oh probably the dev branch contains client api?
then close the thread. (:

**Comment by jhass** [comment]
> oh probably the dev branch contains client api?

Yeah exactly. Let me dig into why it gets stuck though, will be useful for the transition phase after the release to get this right :)

**Comment by jhass** [comment]
Required upstream fix to properly handle this: https://github.com/openid/AppAuth-Android/pull/611

**Comment by tclaus** [comment]
Looks much better with #22 Timeout was originally set tp 60sec with seems to be almost infinite. You'll get a error message either a nice 'timeout' or a hint that pod does not run a v0.8 pod. (Which is currently in beta stage) 
@jhass request to close this issue?

**Comment by jhass** [comment]
No, I want to change the message and more properly detect this case (well, that's likely covered by #22 then) once upstream is fixed to allow to do so.

**Comment by jhass** [comment]
> Timeout was originally set to 60sec

Quite OT here, but I can tell you from four years of professional app development that a connection latency of 30 seconds or more is not unseen on mobile networks, especially as the user is roaming between cells (= walking or driving around).

**Comment by tclaus** [comment]
spyurk.am (now) runs on 7.99 dev branch and should support this App. As v1.0.0 looms on the horizon it is unlikely that unsupported pods will be supported in insporation.
