### ISSUE TITLE
Not able to log in in iOS 

### ISSUE THREAD

**Issue by hanekju** [jhass/insporation#68]
![335B9AF3-EB23-40AE-AA6E-929DBA7FF82C](https://user-images.githubusercontent.com/2135165/201754403-ba331d60-a465-40e4-8c4f-d533ab8a49fa.jpeg)
This is the first time I use the app. I’m not able to log in. The screen told me I’ve to fill in my diaspora ID but it was not akzepted. May be an error by myself.
hanekju@wk3.org

**Comment by jhass** [comment]
Insporation is dependent on the new API only available in the upcoming major diaspora release. Unless your pod is running a preview of that, which wk3.org is not, you cannot use it yet, sorry.
