### ISSUE TITLE
Nightly job don't trigger any more

### ISSUE THREAD

**Issue by tclaus** [jhass/insporation#72]
There are commits / merges to main recently, but the last time the highly job runs was at 11-27-2022.

Most likely the GitHub token in nightly action expired.

**Comment by jhass** [comment]
Pushed an alternative approach, let's see if it works

**Comment by tclaus** [comment]
The nightly job now runs and submits a ne test build to iOS AppStore. 
Nice job.

**Comment by jhass** [comment]
Gonna keep this open for another day to see if skipping also still works
