### ISSUE TITLE
Fastlane

### ISSUE THREAD

**Issue by IzzySoft** [jhass/insporation#73]
Great to see you've established Fastlane structures! There are some issues with its current setup, though:

* [x]  `short_description.txt` must be plain text. No HTML or Markdown supported.
* [x] `full_description.txt` supports Markdown only with my repo. F-Droid has no Markdown support there. If you plan to have your app listed there, better use "simple HTML" instead (F-Droid supports that, my repo supports that, both perform sanitizing on it) You can find some hints on formatting the full description in [my Wiki on Fastlane formattings](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane)
* [ ] some screenshots would be a nice thing to add, see #42 :wink:

**Comment by IzzySoft** [comment]
@jhass any ETA, so I do not nag you here regularly? :wink: I see the "help-wanted" label. Do you want me to provide you updated files for short- and full-desc? I cannot provide any screenshots, though, as I'm not active on Diaspora.

**Comment by tclaus** [comment]
You can provide valid long and short descriptions as a PR if you like.

**Comment by IzzySoft** [comment]
Done. Now (after that's merged) just the screenshots are missing. Guess those one of the contributors could provide? Just 2..5 to give an idea of what to expect would be fully fine.

**Comment by tclaus** [comment]
#74  Merged. Thanks for your contribution.

**Comment by IzzySoft** [comment]
Thanks for merging! Guess you've closed this as screenshots should be dealt with in the linked issue (which was opened 3 years ago :scream:)? OK, I'll follow up there then for them.

**Comment by tclaus** [comment]
Exactly. I am looking forward to add android screenshots. For iOS we have these for a long time.

**Comment by IzzySoft** [comment]
Thanks Thorsten! I'm subscribed to the other issue as well, so if you leave a comment here or there I should hopefully get a notification when they become available so I can integrate them here.
