### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by tclaus** [jhass/insporation#8]
Like that there is a app project for diaspora, 
but I am missing a 'how to start'  here. 

For me I naively cloned the project and run it (under Mac/ iOS) and it suddenly generates tons of iOS files, next I am am not able to log in into my disp.org account (runs 0.7.14) - next I created a account to 'diaspora-fr.org/' which runs 7.99 which I think supports the API which is needed for this app. This also doesn't work.  ( regex in SigninPage doesn't know the '-' in the diaspora ID.. 

So I really like to contribute, but there a lots of questions here.

**Comment by jhass** [comment]
I preemptively enabled iOS support already, just ignore that stuff  for now :P 

Yes, a 0.7.14 pod won't work, as noted at the top of the readme. The commit diaspora-fr.org runs on seems recent enough. Is the `-` what got you stuck on or is there another error?

Sorry, but getting yourself familiar with Flutter is quite the prerequisite to contributing here and teaching you that is not quite in the scope of this project. I'm sure you'll easily find tons of learning material for Flutter on the internet though :)

**Comment by tclaus** [comment]
Thanks for this fast answer - 
On the one side - I get an 'MissingPluginException ... No Implementation found for method getAccessToken' error when I set my Diaspora ID in the App - the message does not indicate, if the Backend supports the right API or if just something is missing in implementation. 
Is there a reliable server, which has all the implementation that is needed to run/test this app? 

On the other side, when I start the app in IOS there are lots of files generated which may not be added to the project and .gitignore should be adapted (at least Podfile.lock should be part of pushed to source repo, some other files not)
I can start a new Issue on this when you like to track this separately.

**Comment by jhass** [comment]
Oh, you're trying iOS! Sorry that wasn't clear to me at all, since I thought I stated quite clearly in the readme that I only ever spent effort on Android until now :) 

That said porting to iOS would be highly appreciated, I think it's as "easy" as writing an adapter for https://github.com/openid/AppAuth-iOS like I did for the Android side of things here: https://github.com/jhass/insporation/blob/main/android/app/src/main/kotlin/jhass/eu/insporation/AppAuthHandler.kt

That's where the `MissingPluginException` is coming from, the binding code implementing `getAccessToken` is missing on iOS :)

**Comment by tclaus** [comment]
So I will try to implement missing parts for the iOS.

**Comment by tclaus** [comment]
It's me again - have had a busy weekend ;-) 
My iOS efforts so far got stuck after sending a request to the diaspora instance and logged in on the web-site. Right after the 'Grant Access to this topic page' and clicking on 'Accept'-Button.
The redirection seems to get refused on mobile safari. 
Any Ideas about the CSP-Problem? Should the redirect be added to the CSP Header? 

<img width="747" alt="Bildschirmfoto 2020-10-20 um 09 25 33" src="https://user-images.githubusercontent.com/501326/96554273-99e1ec00-12b6-11eb-9afb-627bd9cb6fa5.png">

Any Ideas about this? 
A login with Android works.

**Comment by jhass** [comment]
Uff, that's a bummer. Calling @DenSchub or @SuperTux88 for help here as I think they're deeper into our CSP story.

If you got a local development setup of diaspora (handy for debugging but of course quite some additional setup), you can hack around with it in https://github.com/diaspora/diaspora/blob/develop/config/initializers/secure_headers.rb or just disable it entirely for the moment via the config. But we probably should update the CSP policy adhoc in https://github.com/diaspora/diaspora/blob/develop/app/controllers/api/openid_connect/authorizations_controller.rb somewhere... using https://github.com/github/secure_headers/blob/main/docs/per_action_configuration.md

**Comment by jhass** [comment]
If you got a WIP branch to share to trigger the CSP issue, I might be able to sink some time into it :)

**Comment by tclaus** [comment]
My current (early) work is here: 
[adding iOS Support](https://github.com/tclaus/insporation/tree/add_ios_support)

Just enabled iOS and a AppDelegate methodHandler for the auth request.

**Comment by jhass** [comment]
Mmh, using an iOS 14 emulator I have just nothing happening on pressing the button :/

**Comment by tclaus** [comment]
You can set osX Safari on "Developer Mode", then when Simulator Screen is active in Menu "Developer" you can see '(and debug) mobile Safari on Desktop - Safari. 
Right now, I am in the middle of my regular work, but if you like we can remote-talk later this day?

**Comment by jhass** [comment]
Ah, great UX... Let's see how far I get :)

**Comment by skyschub** [comment]
> Calling @denschub

(Browser developer hat) This looks like a Safari-specific weirdness, and [spec ambiguity](https://github.com/w3c/webappsec-csp/issues/8). Interestingly enough, there are Web Platform Tests covering `form-action`, and it actually [looks like all browsers currently do **not** block redirects on `form-action`](https://wpt.fyi/results/content-security-policy/form-action/form-action-src-redirect-blocked.sub.html?label=master&label=experimental&aligned). Also, there is a keyword, `'unsafe-allow-redirects'`, and that [seems to be supported in all browsers](https://wpt.fyi/results/content-security-policy/navigate-to/unsafe-allow-redirects?label=master&label=experimental&aligned), but in tests, this did not resolve this issue. This is likely an issue with Safari treating non-http-protocols differently, but that's hard to tell, and given the status of the spec probably also not worth investigating deeper.

(diaspora\* dev hat) CSP is a mess, and while it has its purpose in our stream pages with lots of external contents, I'm not sure that holds true for authentication-flow pages. While removing CSP entirely from the API pages sounds like a not-good idea, it may be worth investigating if we can just allow everything for `form-action` specifically. Not sure if this even works, tho, and as a fallback, we'd probably have to disable CSP for the entire API auth flow, but... let's try a softer workaround first.

**Comment by jhass** [comment]
Disabling the `form-action` CSP rule for the authorization page entirely helped in my tests: https://github.com/diaspora/diaspora/pull/8166

**Comment by jhass** [comment]
Alright, I updated diaspora.social to that commit. Feel free to make (test) accounts: https://diaspora.social/i/d8b33b925cec

**Comment by tclaus** [comment]
Great - a fresh updated server. Thanks. 
What a catch for one day. 😀

**Comment by jhass** [comment]
Implemented through #10 🙏 Let's have new issues for any open holes / broken functionality.
